### ISSUE TITLE
Skip Invalid Numbers/ Give list of those invalid numbers atfer aswell

### ISSUE THREAD

**Issue by KingTut121** [sjmf/bulk-sms#4]
Code stops when it comes upon an invalid number 

     raise self.exception(method, uri, response, 'Unable to create record')
twilio.base.exceptions.TwilioRestException: HTTP 400 error: Unable to create record: The 'To' number +<phone number> is not a valid phone number.

**Comment by sjmf** [comment]
Please try the following changes to the `sms.py` file:

At the top:

```
 import TwilioRestException from twilio.base.exceptions
```

Then change this code on [line 50](sms.py#L50):

```
        # Send the sms text to the number from the CSV file:
        print("Sending to " + num)
        message = client.messages.create(to=num, from_=from_num, body=sms)
```

to this:

```
        # Send the sms text to the number from the CSV file:
        print("Sending to " + num)
        try:
            message = client.messages.create(to=num, from_=from_num, body=sms)
        except TwilioRestException as e:
            continue
```

Let me know if it works.

**Comment by KingTut121** [comment]
My bad if this is just an simple fix it’s just that I’m new to python lol.
I’ve ran into an invalid syntax error here. What should be done?

**Comment by sjmf** [comment]
Sorry– I'm trying to understand what the issue is, but you're not really giving me enough information. If there's a syntax error, first look at the error message and try and understand which part of the code it's hitting it on. 

For me to be able to help, I need to see the traceback and the code which is throwing the error. 

The 'traceback' is the error message, which I see you've removed from the original post.

At a complete guess, given that you're new to Python, have you mixed tabs and spaces in the file?
